FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y curl ca-certificates openjdk-21-jdk && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN curl -L -o /app/reactor-core.jar \
    https://repo1.maven.org/maven2/io/projectreactor/reactor-core/3.6.6/reactor-core-3.6.6.jar && \
    curl -L -o /app/reactive-streams.jar \
    https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar

COPY TimeStream.java /app/TimeStream.java

RUN javac -cp reactor-core.jar:reactive-streams.jar TimeStream.java

CMD ["sh", "-lc", "java -cp .:reactor-core.jar:reactive-streams.jar TimeStream"]
